# Configuration options are documented at:
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
sudo: false
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
  - 'stable'
script: npm test && (npm run report-coverage || test 1)

notifications:
  email: false
